### PR TITLE
R dbmodelr upgrade v0 2 0

### PR DESCRIPTION
**Pull request by LainPavot**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by fgiacomoni** [comment]
@bgruening, if by any chance, you have two minutes to look at this merge request. Package dependancy for a gxit ;-)

**Comment by LainPavot** [comment]
@dbast , hello,
If you have five minutes, can you check for my PR for this minor update, please?
Thanks!

**Comment by dbast** [comment]
@LainPavot You should have the permissions to merge this yourself.

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Sorry for the late response.

**Comment by LainPavot** [comment]
Thank you!

**Pull request merged**
